language: node_js
node_js:
  - "0.10"

env:
  global:
    - SAUCE_USERNAME=hashspace-bootstrap
    - SAUCE_ACCESS_KEY=5bc971c0-02c9-4091-91ab-937f2b0eb52c
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/logs

before_install:
 - npm install --quiet -g gulp
 - npm install -g coveralls@2.8.0 &> install-coveralls.log

before_script:
 - mkdir -p $LOGS_DIR
 - chmod -R 777 ./build/sauce/connect_start.sh
 - ./build/sauce/connect_start.sh
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - chmod -R 777 ./build/sauce/connect_wait.sh
 - ./build/sauce/connect_wait.sh

script:
 - gulp ci

after_success:
 - cat test-results/*/*/*.info | coveralls && echo "Successfully sent coverage to https://coveralls.io"

after_failure:
 - chmod -R 777 ./build/sauce/connect_logs.sh
 - ./build/sauce/connect_logs.sh